spring.application.name=<<example>>
kafka.servers=<<server>>
kafka.first.group=<<group-name>>
kafka.topic.logs=<<topic-name>>
db.url=<<url>>
db.user=<<user>>
db.password=<<password>>
spring.datasource.url=<spring.datasource>
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
